config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do #ゲストログイン機能
    post "guest_sign_in", to: "sessions#guest_sign_in"
  end

  root to: 'homes#top'
  get 'items/search'
  get 'home/about' => 'homes#about', as: 'about'
  get 'genresearches/genre_search' => 'genresearches#genre_search' #ジャンル検索機能
  get "search" => "searches#search" #検索機能
  get 'users/mypage' => 'users#mypage'
  get 'users/check'
  patch 'users/is_withdraw' #ユーザーステータス

  resources :users, only: [:index, :show, :edit, :update] do
    member do
    get :follows, :followers, :favorites
    end
    resource :relationships, only: [:create, :destroy]
  end


  resources :items, only: [:index, :show, :edit, :update, :new, :create, :destroy] do
    resource :favorites, only: [:index, :create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :notifications, only: [:index,:destroy] #通知機能

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower
  has_many :notifications, dependent: :destroy
  has_one_attached :profile_image

  validates :name, presence: true

  #フォロー機能
 def follow(user_id)
   followers.create(followed_id: user_id)
 end

 def unfollow(user_id)
   followers.find_by(followed_id: user_id).destroy
 end

 def following?(user)
   following_users.include?(user)
 end


  #ユーザーステータス
 def user_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end
 end

 def active_for_authentication?
    super && (is_deleted == false)
 end

 def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
 end

 def get_images
    (images.attached?) ? images : 'no_image.jpg'
 end


# 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

 # ゲストユーザー
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end
# emailでゲストユーザーか判断する
  def guest_user?
     email == GUEST_USER_EMAIL
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @following_users = @user.following_users
    @follower_users = @user.follower_users
    @items = @user.items.page(params[:page]).per(8)
  end

  def mypage
    @user = current_user
    @following_users = @user.following_users
    @follower_users = @user.follower_users
    @items = @user.items.page(params[:page]).per(8)
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.page(params[:page]).per(8)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "更新に成功しました。"
    redirect_to users_mypage_path
    else
    @users = User.all
    render :edit
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.following_users.page(params[:page]).per(8)
  end

  def followers
    user = User.find(params[:id])
    @user = user.follower_users.page(params[:page]).per(8)
  end

  def favorites
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: @user.id).pluck(:item_id)
    @favorite_items = Item.find(favorites)
    @favorite_items = Kaminari.paginate_array(@favorite_items).page(params[:page]).per(8)
  end

  def check
  end

  def is_withdraw
    @user = User.find(current_user.id)
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :is_deleted)
  end

  def ensure_currect_user #投稿者だけが編集できるようにしている
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_favorites.html.erb
<table class="table table-striped">
  <tbody>
    <% favorite_items.each do |item| %>
      <tr>
        <td>
          <% if item.images.attached? %>
            <%= link_to(item) do %>
              <%= image_tag item.get_images[0], size:'50x50' %>
            <% end %>
          <% elsif %>
            <%= link_to(item) do %>
               <%= image_tag item.get_images, size:'50x50' %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to item.name,item_path(item) , class: 'text-dark' %></td>
        <td><%= item.introduction %></td>
        <td id="favorite<%= item.id %>" >
          <%= render 'favorites/favorite', item: item %>
        </td>
        <td>コメント件数:<span id="comment_count"><%= item.comments.count %></span></td>
        <td><%= render "items/static_rate", item: item  %></td>
      </tr>
    <% end %>
    <%= paginate favorite_items %>
  </tbody>
</table>

app/views/users/_item.html.erb
<table class='table'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% items.each do |item| %>
      <tr>
        <td><%= link_to(item.user) do %>
          <%= image_tag item.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to item.name,item %></td>
        <td><%= item.introduction %></td>
        <td id="favorite<%= item.id %>" >
          <%= render 'favorites/favorite', item: item %>
        </td>
        <td>コメント件数:<span id="comment_count"><%= item.comments.count %></span></td>
        <td><%= render "items/static_rate", item: item %></td>
      <% end %>
  </tbody>
</table>

app/views/users/_show.html.erb
<table class="table">
　<tr>
    <td><%= image_tag @user.get_profile_image, size: '50x50' %></td>
  </tr>

  <tr>
    <td>氏名</td>
    <td><%= @user.name %></td>
  </tr>

  <tr>
    <td>一言</td>
    <td><%= @user.introduction %></td>
  </tr>

  <tr>
    <td>フォロー</td>
    <td>
      <%= link_to follows_user_path(@user) do %>
        <%= @user.followers.count %>
      <% end %>
    </td>
  </tr>

  <tr>
    <td>フォロワー</td>
    <td>
      <%= link_to followers_user_path(@user) do %>
        <%= @user.followeds.count %>
      <% end %>
    </td>
  </tr>

  <tr>
    <td>会員ステータス</td>
    <td><% if @user.is_deleted == false %>
        有効
        <% else %>
        退会
        <% end %>
    </td>
  </tr>

  <tr>
    <% if current_user != @user %>
      <% if current_user.following?(@user) %>
        <td><%= link_to "フォローを外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-danger" %></td>
      <% else %>
        <td><%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "byn btn-success" %></td>
      <% end %>
    <% end %>
  </tr>

  <tr>
    <% if user_signed_in? %>
  　　　<% if current_user.admin? %>
        <td>
          <%= form_with model: @user, url:user_path(@user), method: :patch, local: true do |f| %>
            <div class="form-group">
              <%= f.label :会員ステータス %>
              <%= f.radio_button :is_deleted, :false %>
              <%= f.label :is_deleted, "有効" %>
              <%= f.radio_button :is_deleted, :true %>
              <%= f.label :is_deleted, "退会" %>
              <%= f.submit "変更を保存", class: 'btn btn-success' %>
            </div>
          <% end %>
       </td>
      <% end %>
    <% end %>
  </tr>
</table>

app/views/users/check.html.erb
<div class="container mt-5">
  <div class='row'>
    <div class="edit shadow col-md-7">
      <div class = text-center>
      <h1 class ="check messege">本当に退会しますか？</h1>
      <p>
         退会すると、ユーザー登録情報や<br>
         これまでの投稿履歴が閲覧できなくなります。<br>
         退会する場合は、「退会する」をクリックしてください。
      </p>
      <%= link_to "退会しない", users_mypage_path(@user), :class => "btn btn-primary ms-3" %>
      <%= link_to "退会する", users_is_withdraw_path(@user), method: :patch, :class => "btn btn-danger ms-3", data: { confirm: "本当に退会しますか？" }  %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='container mt-5'>
  <div class='row'>
    <div class="edit shadow col-md-7">
     <h2>User info</h2>

      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control name" %>
        </div>

        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
        </div>

        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>

        <div class="text-center">
          <%= f.submit class: 'btn btn-info' %>
        </div>
      <% end %>

      <div class="text-center mt-2">
        <%= link_to "退会する", users_check_path, class: "btn btn-danger ms-3" %>
      </div>

    </div>
  </div>
</div>

app/views/users/favorites.html.erb
  <div class="container mt-3">
    <h3 class="fas fa-heart col-md-9  text-secondary">いいね一覧</h3>

      <div class="row">
        <% @favorite_items.each do |item| %>
          <div class="row media-card shadow" style="width: 370px">
            <div class="col-md-5 text-center">
              <% if item.rakuten_image.blank? %>
                <%= link_to item_path(item) do %>
                  <%= image_tag 'no_image.jpg', class: "border border-secondary", size: '130x130' %></br>
                <% end %>
              <% else %>
                <%= link_to item_path(item) do %>
                  <%= image_tag item.rakuten_image, class: "border border-secondary", size: '130x130' %></br>
                <% end %>
              <% end %>
              <p>&emsp;<%= link_to "商品を見る→",item_path(item), class: "text-dark" %></p>
            </div>

            <div class="col-md-7">
              <div class="line">商品名：<%= item.name.truncate(9, omission: '...')%></div>
              <div class="line">投稿日時：<%= item.created_at.strftime('%Y/%m/%d') %></div>
              <div class="line">投稿者：<%= link_to item.user.name, item.user, class: "text-dark"%></div>
              <div class="line" id="favorite<%= item.id %>"><%= render 'favorites/favorite', item: item %></div>
            </div>
          </div>
        <% end %>
      </div>

      <div class="col-md-10">
        <%= paginate @favorite_items %>
      </div>
  </div>

app/views/users/followers.html.erb
<div class="container mt-3">
  <h3 class="fas fa-users text-secondary">フォロワー一覧</h3>

  <% @user.each do |user| %>
    <div class= "row user-group shadow ">
      <div class="col-md-2 text-center">
        <%= image_tag user.get_profile_image, class: "rounded-circle",size:"50x50"  %></br>
        <%= user.name %>
      </div>

      <div class="col-md-2 text-center">
        <span class="badge badge-primary">フォロー</span>
        <%= link_to follows_user_path(user), class: 'text-dark' do %>
          <p><%= user.followers.count %></p>
        <% end %>
      </div>

      <div class="col-md-2 text-center">
        <span class="badge badge-info">フォロワー</span>
        <%= link_to followers_user_path(user), class: 'text-dark' do %>
          <p><%= user.followeds.count %></p>
        <% end %>
      </div>

      <div class="col-md-2 text-center">
        <%= link_to 'Show', user ,class: 'btn btn--orange btn--circle btn--circle-a btn--shadow'%>
      </div>

      <div class="sample col-md-3 text-center">
        <% if current_user != user %>
          <% if current_user.following?(user) %>
            <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-outline-info btn--radius" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-info btn--radius" %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="mx-auto">
    <%= paginate @user %>
  </div>

</div>

app/views/users/follows.html.erb
<div class="container mt-3">
  <h3 class="fas fa-users text-secondary">フォロー一覧</h3>

  <% @users.each do |user| %>
    <div class= "row user-group shadow ">
      <div class="col-md-2 text-center">
        <%= image_tag user.get_profile_image, class: "rounded-circle",size:"50x50"  %></br>
        <%= user.name %>
      </div>

      <div class="col-md-2 text-center">
        <span class="badge badge-primary">フォロー</span>
        <%= link_to follows_user_path(user), class: 'text-dark' do %>
          <p><%= user.followers.count %></p>
        <% end %>
      </div>

      <div class="col-md-2 text-center">
        <span class="badge badge-info">フォロワー</span>
        <%= link_to followers_user_path(user), class: 'text-dark' do %>
          <p><%= user.followeds.count %></p>
        <% end %>
      </div>

      <div class="col-md-2 text-center">
        <%= link_to 'Show', user ,class: 'btn btn--orange btn--circle btn--circle-a btn--shadow'%>
      </div>

      <div class="sample col-md-3 text-center">
        <% if current_user != user %>
          <% if current_user.following?(user) %>
            <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-outline-info btn--radius" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-info btn--radius" %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="mx-auto">
    <%= paginate @users %>
  </div>

</div>

app/views/users/index.html.erb
<div class="container mt-3">
  <h3 class="fas fa-users text-secondary">ユーザー一覧</h3>

  <% @users.each do |user| %>
    <div class= "row user-group shadow">
      <div class="col-md-2 text-center">
        <%= image_tag user.get_profile_image, class: "rounded-circle",size:"50x50"  %></br>
        <%= user.name %>
      </div>

      <div class="col-md-2 text-center">
        <span class="badge badge-primary">フォロー</span>
        <%= link_to follows_user_path(user), class: 'text-dark' do %>
          <p><%= user.followers.count %></p>
        <% end %>
      </div>

      <div class="col-md-2 text-center">
        <span class="badge badge-info">フォロワー</span>
        <%= link_to followers_user_path(user), class: 'text-dark' do %>
          <p><%= user.followeds.count %></p>
        <% end %>
      </div>

      <div class="col-md-2 text-center">
        <%= link_to 'Show', user ,class: 'btn btn--orange btn--circle btn--circle-a btn--shadow'%>
      </div>

      <div class="sample col-md-3 text-center">
        <% if current_user != user %>
          <% if current_user.following?(user) %>
            <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-outline-info btn--radius" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-info btn--radius" %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="mx-auto">
    <%= paginate @users %>
  </div>

</div>

app/views/users/mypage.html.erb
<div class="container mt-3">
  <div class="row">
    <h3 class="fas fa-home  col-md-8 text-secondary">マイページ</h3>

    <div class="mypage shadow col-md-8">
      <div class="tabs">
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link active text-dark" data-toggle="tab" href="#section1">my情報</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark" data-toggle="tab" href="#section2">my投稿</a>
          </li>
        </ul>

        <div class="tab-content">
          <div id="section1" class="tab-pane fade show active">
            <div class="row">
              <div class="col-md-12 text-center mt-2">
                <%= image_tag @user.get_profile_image, class: "rounded-circle", size: '150x150' %></br>
                <%= @user.name %>
              </div>

              <div class="col-md-12">
                <%= link_to favorites_user_path(@user) do %>
                  <h5 class="text-dark">♡いいね一覧へ</h5>
                <% end %>
                <h5>・紹介文</h5>
                <div class="text-body">
                  <%= @user.introduction %>
                </div>
              </div>

              <div class="uses col-md-6 text-center mt-4">
                フォロー
              </div>
              <div class="uses col-md-6 text-center mt-4">
                <%= link_to follows_user_path(@user), class: 'text-dark' do %>
                  <%= @user.followers.count %>
                <% end %>
              </div>

              <div class="forr col-md-6 text-center">
                フォロワー
              </div>
              <div class="forr col-md-6 text-center">
                <%= link_to followers_user_path(@user), class: 'text-dark' do %>
                  <%= @user.followeds.count %>
                <% end %>
              </div>

              <div class="uses col-md-6 text-center">
                ユーザーステータス
              </div>
              <div class="uses col-md-6 text-center">
                <% if @user.is_deleted == false %>
                  有効
                <% else %>
                  退会
                <% end %>
              </div>
            <!--ゲストユーザーの場合表示しない-->
              <% if user_signed_in? %>
                <% unless current_user.guest_user? %>
                  <div class="compile col-md-12 text-center">
                    <%= link_to "編集する", edit_user_path(@user), class: 'btn btn--orange btn--radius'%>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>

          <div id="section2" class="tab-pane fade show list">
            <table class="table table-striped">
              <tbody>
              <% @items.each do |item| %>
                <tr>
                  <td>
                    <% if item.rakuten_image.blank? %>
                      <%= image_tag 'no_image.jpg', class: "border border-secondary", size: '50x50' %>
                    <% else %>
                      <%= image_tag item.rakuten_image, class: "border border-secondary", size: '50x50' %>
                    <% end %>
                  </td>
                  <td><%= link_to item.name.truncate(12, omission: '...'),item, class: "text-dark"%></td>
                  <td id="favorite<%= item.id %>" >
                    <%= render 'favorites/favorite', item: item %>
                  </td>
                  <td>コメント件数:<span id="comment_count"><%= item.comments.count %></span></td>
                </tr>
              <% end %>
              </tbody>
            </table>
            <%= paginate @items %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-3">
  <div class="row">
  <h3 class="fas fa-home  col-md-7 text-secondary">ユーザー詳細</h3>

　  <div class="enduser shadow col-md-8">
　    <div class="tabs">
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link active text-dark" data-toggle="tab" href="#section1">ユーザー情報</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark" data-toggle="tab" href="#section2">ユーザー投稿</a>
          </li>
        </ul>

        <div class="tab-content">
          <div id="section1" class="tab-pane fade show active">
            <div class="row">
              <div class="col-md-12 text-center mt-2">
                <%= image_tag @user.get_profile_image, class: "rounded-circle", size: '150x150' %></br>
                <%= @user.name %>
              </div>

              <div class="col-md-12">
                <h5>・紹介文</h5>
                <div class="text-body">
                  <%= @user.introduction %>
                </div>
              </div>

              <div class="uses col-md-6 text-center mt-4">
                フォロー
              </div>
              <div class="uses col-md-6 text-center mt-4">
                <%= link_to follows_user_path(@user), class: 'text-dark' do %>
                  <%= @user.followers.count %>
                <% end %>
              </div>

              <div class="forr col-md-6 text-center">
                フォロワー
              </div>
              <div class="forr col-md-6 text-center">
                <%= link_to followers_user_path(@user), class: 'text-dark' do %>
                  <%= @user.followeds.count %>
                <% end %>
              </div>

              <div class="uses col-md-6 text-center">
                ユーザーステータス
              </div>
              <div class="uses col-md-6 text-center">
                <% if @user.is_deleted == false %>
                有効
                <% else %>
                退会
                <% end %>
              </div>

              <div class="col-md-12 text-center mt-3">
                <% if current_user != @user %>
                  <% if current_user.following?(@user) %>
                    <%= link_to "フォローを外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-outline-info btn--radius" %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(@user.id), method: :post,  class: "btn btn-info btn--radius" %>
                  <% end %>
                <% end %>
              </div>
              <!--管理者がログイン時のみ表示、ユーザーステータスを変更できる-->
              <% if user_signed_in? %>
  　　          　<% if current_user.admin? %>
                  <div class="col-md-12 text-center">
                    <%= form_with model: @user, url:user_path(@user), method: :patch, local: true do |f| %>
                      <div class="form-group">
                        <%= f.label :ユーザーステータス %>
                        <%= f.radio_button :is_deleted, :false %>
                        <%= f.label :is_deleted, "有効" %>
                        <%= f.radio_button :is_deleted, :true %>
                        <%= f.label :is_deleted, "退会" %>
                        <%= f.submit "変更を保存", class: 'btn btn--orange btn--radius', data: { confirm: "【確認】ステータスを変更しますか？" } %>
                      </div>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>

          <div id="section2" class="tab-pane fade show list">
            <table class="table table-striped">
              <tbody>
                <% @items.each do |item| %>
                <tr>
                  <td>
                  <% if item.rakuten_image.blank? %>
                    <%= image_tag 'no_image.jpg', class: "border border-secondary", size: '50x50' %>
                  <% else %>
                    <%= image_tag item.rakuten_image, class: "border border-secondary", size: '50x50' %>
                  <% end %>
                  </td>
                  <td><%= link_to item.name.truncate(12, omission: '...'),item, class: "text-dark" %></td>
                  <td id="favorite<%= item.id %>" >
                    <%= render 'favorites/favorite', item: item %>
                  </td>
                  <td>コメント件数:<span id="comment_count"><%= item.comments.count %></span></td>
                </tr>
                <% end %>
              </tbody>
             </table>
             <%= paginate @items %>
           </div>
         </div>

      </div>
    </div>
  </div>
</div>