config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do #ゲストログイン機能
    post "guest_sign_in", to: "sessions#guest_sign_in"
  end

  root to: 'homes#top'
  get 'items/search'
  get 'home/about' => 'homes#about', as: 'about'
  get 'genresearches/genre_search' => 'genresearches#genre_search' #ジャンル検索機能
  get "search" => "searches#search" #検索機能
  get 'users/mypage' => 'users#mypage'
  get 'users/check'
  patch 'users/is_withdraw' #ユーザーステータス

  resources :users, only: [:index, :show, :edit, :update] do
    member do
    get :follows, :followers, :favorites
    end
    resource :relationships, only: [:create, :destroy]
  end


  resources :items, only: [:index, :show, :edit, :update, :new, :create, :destroy] do
    resource :favorites, only: [:index, :create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :notifications, only: [:index,:destroy] #通知機能

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "User" #検索ワードがuserの場合
      @users = User.looks(params[:search], params[:word]).page(params[:page]).per(8)
    else #userでない場合(item)の場合
      @items = Item.looks(params[:search], params[:word]).page(params[:page]).per(8)
    end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_genre.html.erb
<div class="genre_search">
    <tr>
    <div class="form-group">
    <%= form_with url: searches_genre_search_path, method: :get do |f| %>
    <%= f.label :ジャンル検索 %>
    <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
    <%= f.submit "検索", class: 'btn btn-info' %>
    <% end %>
    </div>
   </tr>
</div>

app/views/searches/_search.html.erb
<div class="search_form">
  <%= form_with url: search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word %>
    <%= f.select :range, options_for_select([['User'], ['Item']]) %>
    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
    <%= f.submit "検索", class: "btn-sm btn-light" %>
  <% end %>
</div>

app/views/searches/search.html.erb
<% if @range == "User" %>
<!--検索ワードがuserの時-->
  <div class="container mt-3">
    <h3>ユーザー検索ワード "<%= @word %>"</h3>
    <h5>検索結果"<%= @users.count %>"件</h5>

    <% @users.each do |user| %>
      <div class= "row user-group shadow ">
        <div class="col-md-2 text-center">
          <%= image_tag user.get_profile_image, class: "rounded-circle",size:"50x50"  %></br>
          <%= user.name %>
        </div>

        <div class="col-md-2 text-center">
          <span class="badge badge-primary">フォロー</span>
          <%= link_to follows_user_path(user), class: 'text-dark' do %>
            <p><%= user.followers.count %></p>
          <% end %>
        </div>

        <div class="col-md-2 text-center">
          <span class="badge badge-info">フォロワー</span>
          <%= link_to followers_user_path(user), class: 'text-dark' do %>
            <p><%= user.followeds.count %></p>
          <% end %>
        </div>

        <div class="col-md-2 text-center">
          <%= link_to 'Show', user ,class: 'btn btn--orange btn--circle btn--circle-a btn--shadow'%>
        </div>

        <div class="sample col-md-3 text-center">
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-outline-info btn--radius" %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-info btn--radius" %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="mx-auto">
      <%= paginate @users %>
    </div>
  </div>

<% else %>
<!--検索対象モデルがUserではない時(= 検索対象モデルがitemの時) -->
  <div class="container mt-3">
    <h2>商品検索ワード "<%= @word %>"</h2>
    <h5>検索結果"<%= @items.count %>"件</h5>

    <div class="row">
    <% @items.each do |item| %>
      <div class="row media-card shadow" style="width: 370px">
        <div class="col-md-5 text-center">
          <% if item.rakuten_image.blank? %>
            <%= link_to item_path(item) do %>
              <%= image_tag 'no_image.jpg', class: "border border-secondary", size: '130x130' %></br>
            <% end %>
          <% else %>
            <%= link_to item_path(item) do %>
              <%= image_tag item.rakuten_image, class: "border border-secondary", size: '130x130' %></br>
            <% end %>
          <% end %>
          <p>&emsp;<%= link_to "商品を見る→",item_path(item), class: "text-dark" %></p>
        </div>

        <div class="col-md-7">
          <div class="line">商品名：<%= item.name.truncate(9, omission: '...')%></div>
          <div class="line">投稿日時：<%= item.created_at.strftime('%Y/%m/%d') %></div>
          <div class="line">投稿者：<%= link_to item.user.name, item.user, class: "text-dark"%></div>
          <div class="line" id="favorite<%= item.id %>"><%= render 'favorites/favorite', item: item %></div>
        </div>
      </div>
    <% end %>
    </div>

    <div class="col-md-10">
      <%= paginate @items %>
    </div>
  </div>
<% end %>