config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do #ゲストログイン機能
    post "guest_sign_in", to: "sessions#guest_sign_in"
  end

  root to: 'homes#top'
  get 'items/search'
  get 'home/about' => 'homes#about', as: 'about'
  get 'genresearches/genre_search' => 'genresearches#genre_search' #ジャンル検索機能
  get "search" => "searches#search" #検索機能
  get 'users/mypage' => 'users#mypage'
  get 'users/check'
  patch 'users/is_withdraw' #ユーザーステータス

  resources :users, only: [:index, :show, :edit, :update] do
    member do
    get :follows, :followers, :favorites
    end
    resource :relationships, only: [:create, :destroy]
  end


  resources :items, only: [:index, :show, :edit, :update, :new, :create, :destroy] do
    resource :favorites, only: [:index, :create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :notifications, only: [:index,:destroy] #通知機能

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user
  belongs_to :genre
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  has_one :notification, as: :subject, dependent: :destroy

  #画像複数投稿
  has_many_attached :images
  #動画投稿機能
  has_one_attached :video



  #ソート機能
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :favorites_count, -> {order(favorites: :desc)}
  scope :star_count, -> {order(star: :desc)}

  validates :name, presence: true
  validates :introduction, presence: true
  #いいね機能
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def get_images
    (images.attached?) ? images : 'no_image.jpg'
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end


  #検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @item = Item.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @item = Item.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @item = Item.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @item = Item.where("name LIKE?","%#{word}%")
    else
      @item = Item.all
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
     before_action :authenticate_user!

  def new
    if Item.where(user_id:current_user.id,rakuten_code:params[:rakuten_code]).count == 0 #ユーザーが商品を投稿済みか確認
      @item = Item.new(rakuten_image:params[:rakuten_image][0],rakuten_name:params[:rakuten_name],rakuten_url:params[:rakuten_url],rakuten_introduction:params[:rakuten_introduction],rakuten_code:params[:rakuten_code])
    else #投稿済みの場合ページ遷移しない
     redirect_to request.referer,flash: {alert: "この商品は投稿済みです" }
    end
  end

  def show
    @item = Item.find(params[:id])
    @user = @item.user
    @comment = Comment.new
  end

  def index
    if params[:latest]
    @item = Item.latest.page(params[:page]).per(8)
    elsif params[:old]
    @item = Item.old.page(params[:page]).per(8)
    elsif params[:favorites_count]
    @item = Item.favorites_count.page(params[:page]).per(8)
    elsif params[:star_count]
    @item = Item.star_count.page(params[:page]).per(8)
    else
    @item = Item.page(params[:page]).per(8)
    end

    @user = current_user
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
    flash[:notice] = "投稿に成功しました。"
    redirect_to item_path(@item.id)
    else
    @items = Item.all
    render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
     flash[:notice] = "更新に成功しました。"
     redirect_to item_path(@item.id)
    else
     @items = Item.all
     render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to items_path
  end

  def search
    if params[:keyword]
      @item = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword])
    end
  end


  private

  def item_params
    params.require(:item).permit(:name, :introduction, :star,:favorites, :genre_id, :video,:rakuten_image, :rakuten_name, :rakuten_url, :rakuten_introduction,:rakuten_code,images: [])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.erb
<% @item.first(10).each do |item| %>
  <div class="list-group">
    <%= image_tag (item['smallImageUrls'][0]) %>
    <%= link_to item.name, "#{item.url}" %>
    <%= number_with_delimiter(item.price) %>円
  </div>
<% end %>

app/views/items/_static_rate.html.erb
<div id="star_<%= item.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#star_<%= item.id %>');
  if (elem == null) return;

  elem.innerHTML = "評価：";
  let opt = {
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= item.star %>",
    readOnly: true,
  };
  raty(elem, opt);
});
</script>

app/views/items/_varidation.html.erb
<% if item.errors.any? %>
  <%= item.errors.count %>件のエラーが発生しました
  <ul>
    <% item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/items/edit.html.erb
<div class='container col-md-8 float-left mt-2'>

  <h2 class="text-center text-secondary">商品編集</h2>
  <div class="col-md-12 edit">
    <%= render 'varidation', item: @item %>
    <%= form_with model:@item, local:true do |f| %>

      <% unless @item.rakuten_image.blank? %>
        <div class="form-group">
          <%= image_tag @item.rakuten_image %>
          <%= f.hidden_field :rakuten_image, :value => @item.rakuten_image %>
        </div>
      <% end %>

        <div class="form-group">
          <%= f.label :rakuten_code %>
          <%= f.text_field :rakuten_code, class: "form-control name",readonly:true %>
        </div>

        <div class="form-group">
          <%= f.label :rakuten_name %>
          <%= f.text_field :rakuten_name, class: "form-control name",readonly:true %>
        </div>

        <div class="form-group">
          <%= f.label :rakuten_url %>
          <%= f.text_field :rakuten_url, class: "form-control name",readonly:true %>
        </div>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control introduction" %>
        </div>

        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>

        <div class="form-group">
          <%= f.label :ジャンル %>
          <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
        </div>
      <!--一度した評価は変えられない-->
      <% if @item.id.nil? %>
        <div class="form-group" id="star">
          <%= f.label :star %>
          <%= f.hidden_field :star, id: :review_star, class: 'form-control' %>
          <div id="post_raty"></div>
        </div>
        <script>
          $(document).on('turbolinks:load', function() {
           let elem = document.querySelector('#post_raty');
            if (elem == null) return;
            elem.innerHTML = ""
            let opt = {
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            scoreName: 'book[star]',
            };
           raty(elem, opt);
          });
        </script>
      <% else %>
        <div class="form-group">
         <%= render "static_rate", item: @item %>
        </div>
      <% end %>

        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :images, class: "form-control-file image", accept: 'image/*', multiple: true %>
        </div>

        <div class="form-group">
          <%= f.label :video %>
          <%= f.file_field :video, class: "form-control-file video", accept: 'video/*' %>
        </div>

        <div class="form-group text-center">
         <%= f.submit class: "btn btn--orange" %>
        </div>

    <% end %>
  </div>
</div>

app/views/items/index.html.erb
  <div class='container'>

    <h2 class="fas fa-cat text-secondary mt-3">投稿一覧</h2>
    <nav class="nav nav-items col-md-10">
      <%= link_to '新しい順', items_path(latest: "true"), class: "nav-link list text-dark"%>
      <%= link_to '古い順', items_path(old: "true"), class: "nav-link list text-dark" %>
      <%= link_to '評価の高い順', items_path(star_count: "true"), class: "nav-link list text-dark" %>
    </nav>

    <div class="row">
      <% @item.each do |item| %>
        <div class="row media-card shadow" style="width: 370px">
          <div class="col-md-5 text-center">
            <% if item.rakuten_image.blank? %>
              <%= link_to item_path(item) do %>
                <%= image_tag 'no_image.jpg', class: "border border-secondary", size: '130x130' %></br>
              <% end %>
            <% else %>
              <%= link_to item_path(item) do %>
                <%= image_tag item.rakuten_image, class: "border border-secondary", size: '130x130' %></br>
              <% end %>
            <% end %>
            <p>&emsp;<%= link_to "商品を見る→",item_path(item), class: "text-dark" %></p>
          </div>

          <div class="col-md-7">
            <div class="line">商品名：<%= item.name.truncate(9, omission: '...')%></div>
            <div class="line">投稿日時：<%= item.created_at.strftime('%Y/%m/%d') %></div>
            <div class="line">投稿者：<%= link_to item.user.name, item.user, class: "text-dark"%></div>
            <div class="line" id="favorite<%= item.id %>"><%= render 'favorites/favorite', item: item %></div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-md-10">
      <%= paginate @item %>
    </div>

  </div>

app/views/items/new.html.erb
<div class='container col-md-8 float-left mt-2'>
  <h2 class="text-center text-secondary">新規投稿</h2>

  <div class="col-md-12 edit">
    <%= render 'varidation', item: @item %>
    <%= form_with model:@item, local:true do |f| %>
    <!--楽天から引用したものは編集できない-->
      <div class="form-group">
        <%= image_tag @item.rakuten_image %>
        <%= f.hidden_field :rakuten_image, :value => @item.rakuten_image %>
      </div>

      <div class="form-group">
        <%= f.label :rakuten_code %>
        <%= f.text_field :rakuten_code, class: "form-control name",readonly:true %>
      </div>

      <div class="form-group">
        <%= f.label :rakuten_name %>
        <%= f.text_field :rakuten_name, class: "form-control name",readonly:true %>
      </div>

      <div class="form-group">
        <%= f.label :rakuten_url %>
        <%= f.text_field :rakuten_url, class: "form-control name",readonly:true %>
      </div>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control introduction" %>
      </div>

      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>

      <div class="form-group">
        <%= f.label :ジャンル %>
        <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
      </div>

      <div class="form-group" id="star">
        <%= f.label :star %>
        <%= f.hidden_field :star, id: :review_star, class: 'form-control' %>
      <div id="post_raty"></div>
      </div>
        <script>
          $(document).on('turbolinks:load', function() {
           let elem = document.querySelector('#post_raty');
            if (elem == null) return;
            elem.innerHTML = ""
            let opt = {
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            scoreName: 'item[star]',
            };
           raty(elem, opt);
          });
        </script>

      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :images, class: "form-control-file image", accept: 'image/*', multiple: true %>
      </div>

      <div class="form-group">
        <%= f.label :video %>
        <%= f.file_field :video, class: "form-control-file video", accept: 'video/*' %>
      </div>

      <div class="form-group text-center">
        <%= f.submit class: "btn btn--orange" %>
      </div>

    <% end %>
  </div>
</div>

app/views/items/search.html.erb
<div class='container col-md-8 mt-2 float-left'>
  <h2 class="text-center text-secondary">商品を検索</h2>
  <div class="search-box">
    <%= form_with url: items_search_path, method: :get, local: true do |f| %>
      <div class="form-group">
        <%= f.text_field :keyword, value: params[:keyword], class: "form-control" %>
        <%= f.submit '製品名を検索', class: "form-control btn btn--orange" %>
      </div>
    <% end %>
    <!--楽天の商品を検索-->
    <% if @item.present? %>
      <% @item.first(10).each do |item| %>
        <div class="list-group mt-3">
          <%= link_to "#{item.url}" do %>
            <%= image_tag (item['smallImageUrls'][0]) %>
          <% end %>
          <%= link_to new_item_path(rakuten_image:item.medium_image_urls,rakuten_name:item.name,rakuten_url:item.url,rakuten_introduction:item.params["itemCaption"],rakuten_code:item.params["itemCode"]) do %>
            <%= item.name %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<div class='container  col-md-11'>
  <h2 class="fas fa-cat text-secondary mt-3">投稿詳細</h2>

  <div class="row edit mt-2">
    <div class='col-md-6'>
      <!--投稿者か管理者なら編集可能-->
      <% if user_signed_in? %>
        <% if current_user == @user || current_user.admin? %>
          <%= link_to "編集", edit_item_path, class: 'btn btn--orange' %>
          <%= link_to '削除', @item, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-outline-danger"%>
        <% end %>
      <% end %>
      <h5><%= @item.rakuten_name %></h5>
    </div>

    <div class='text-center col-md-6'>
      <h5>投稿者</h5>
      <%= link_to user_path(@user) do %>
        <div class='user-badge text-dark text-left shadow'>
          <%= image_tag @user.get_profile_image, class: "rounded-circle",size:"50x50"  %>
          &nbsp;<%= @user.name %>
        </div>
      <% end %>
    </div>

    <div class="media col-md-12 mt-3">
      <img class="rounded-lg">
        <% if @item.rakuten_image.blank? %>
          <%= image_tag 'no_image.jpg', class: "border border-secondary", size: '200x200' %>
        <% else %>
          <%= image_tag @item.rakuten_image, class: "border border-secondary", size: '200x200' %>
        <% end %>
      </img>
      <div class="media-body">
        <p class= "border-bottom">商品名：<%= @item.name %></p>
        <p class= "border-bottom">投稿日時：<%= @item.created_at.strftime('%Y/%m/%d') %></p>
        <p class= "border-bottom">URL：<%= link_to @item.rakuten_url, @item.rakuten_url %></p>
        <p class= "border-bottom">ジャンル：<%= @item.genre.name %></p>
        <p class="border-bottom" id="favorite<%= @item.id %>"><%= render 'favorites/favorite', item: @item %></p>
        <p><%= render "static_rate", item: @item %></p>
      </div>
    </div>

    <div class='col-md-12 item'>
      <h5>・商品説明</h>
      <p class="mt-2"><%= @item.introduction %></p>
    </div>
   <!--画像がなければ表示しない-->
   <% if @item.images.attached? %>
    <div class='col-md-12 item'>
      <h5>・商品画像</h>
      <div class="sliders mx-auto" style="width:480px;">
        <% @item.images.each do |image| %>
          <%= image_tag image.variant(resize:'480x300').processed ,style: "height: 300px;"%>
        <% end %>
      </div>
    </div>
   <% end %>
   <!--動画がなければ表示しない-->
   <% if @item.video.attached? %>
    <div class='col-md-12 item'>
      <h5>・商品動画</h>
      <div class='text-center'>
      <video src="<%= rails_blob_path(@item.video) %>" type="video/mp4" controls width="480" height="300"></video>
      </div>
    </div>
   <% end %>

    <div class='col-md-12 item'>
      <div id="comments">
        <%= render 'comments/show', item: @item, comments: @comment, user: @user %>
      </div>
    </div>

    <div class='col-md-12 item'>
      <div id="comment-form">
        <%= render 'comments/form', item: @item, comments: @comment, user: @user %>
      </div>
    </div>

  </div>
</div>