config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do #ゲストログイン機能
    post "guest_sign_in", to: "sessions#guest_sign_in"
  end

  root to: 'homes#top'
  get 'items/search'
  get 'home/about' => 'homes#about', as: 'about'
  get 'genresearches/genre_search' => 'genresearches#genre_search' #ジャンル検索機能
  get "search" => "searches#search" #検索機能
  get 'users/mypage' => 'users#mypage'
  get 'users/check'
  patch 'users/is_withdraw' #ユーザーステータス

  resources :users, only: [:index, :show, :edit, :update] do
    member do
    get :follows, :followers, :favorites
    end
    resource :relationships, only: [:create, :destroy]
  end


  resources :items, only: [:index, :show, :edit, :update, :new, :create, :destroy] do
    resource :favorites, only: [:index, :create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :notifications, only: [:index,:destroy] #通知機能

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
  	  <div class="pull-left">
      <%= link_to 'Back','javascript:history.back()',class: "text-dark" %>
      |&nbsp;<%= link_to 'Top',root_path,class: "text-dark" %>
      </div>
    	<div class='mx-auto'>
    		<p class="foot">Cappy Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #FFAD90" >
    <div class="container">
      <a class="navbar-brand" href="/"><span>Cappy</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
           <%= render 'searches/search' %>
          </li>

        　<li>
            <%= link_to notifications_path, class: 'nav-link text-light' do %>
              <% if current_user.notifications.where(checked: false).exists? %>
                <i class="fa-sharp fa-solid fa-bell fa-beat text-danger"></i>
              <% else %>
                <i class="fa-sharp fa-solid fa-bell"></i>
              <% end %>
                通知一覧
            <% end %>
          </li>

          <li>
            <%= link_to users_mypage_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Mypage
            <% end %>
          </li>

          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>

        <% else %>

          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>

          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> Sign up
            <% end %>
          </li>

          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>

    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
  <div class="sidebar col-md-12 shadow mt-4">
    <div>
      <%= link_to notifications_path, class: 'nav-link text-dark' do %>
        <i class="fa-sharp fa-solid fa-bell"></i> 通知一覧
      <% end %>
    </div>

    <div>
     <%= link_to users_mypage_path(current_user),class: 'nav-link text-dark' do %>
       <i class="fas fa-home"></i> マイページ
     <% end %>
    </div>

    <div>
     <%= link_to users_path,class: 'nav-link text-dark' do %>
       <i class="fas fa-users"></i> ユーザー一覧
     <% end %>
    </div>

    <div>
     <%=  link_to items_path ,class: 'nav-link text-dark' do %>
       <i class="fas fa-cat"></i> 投稿一覧
     <% end %>
    </div>

    <div>
     <%=  link_to items_search_path ,class: 'nav-link text-dark' do %>
       <i class="fas fa-book-open"></i> 新規投稿
     <% end %>
    </div>

    <div>
      <%= render "genresearches/genre"  %>
    </div>
  </div>

  <div class="mt-2">
    <div class="sidebar shadow col-md-12 text-left">
    <h6 class="text-dark">&emsp;新着リスト</h6>
      <table class="table-striped sidetable" >
        <tbody>
          <% @newitem.each do |item| %>
          <tr>
            <td>・<%= link_to item.name.truncate(12, omission: '...'),item_path(item), class: 'text-dark' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cappy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src="https://kit.fontawesome.com/d1642612f4.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>

      <div class="row">
        <% if user_signed_in? %>
          <div class="col-md-2 offset-1 mt-4">
            <%= render 'layouts/sidebar' %>
          </div>
          <div class="col-md-8 mx-auto">
            <%= yield %>
          </div>
        <% else %>
          <div class="col-md-8 mx-auto">
            <%= yield %>
          </div>
        <% end %>
      </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

<script>
$(function() {
  $('.sliders').slick({
    prevArrow: '<button class="slide-arrow prev-arrow"></button>',
    nextArrow: '<button class="slide-arrow next-arrow"></button>'
  });
});

$(document).on('turbolinks:load',function() {
  $('.slider').slick({
      arrows: false,  //ボタン非表示
      autoplay: true, //自動再生
      autoplaySpeed: 3000, //再生スピード
  });
});
</script>